### ISSUE TITLE
Anncouncement: FAQ freeze

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo.github.io#116]
As I am currently working on the german localization of the FAQ I would kindly ask the team not to modify the FAQ on `master` for the time being. 
I will try to do this in a short time frame and a stable situation makes it easier.

Once I am done I will close this issue and you are more than welcome to fix my typos and further improve it.
Thanks!

**Comment by SammysHP** [comment]
Your last pull request was based on your master, but your previous commits were squashed. Working with a dedicated branch would have helped. ;)

**Comment by Lineflyer** [comment]
The github UI does not offer any useful function for management of branches in your fork AFAIK  (other than that you can create PRs between the branches). 
However I will just work on my local branch, verify the result is working and afterwards commit the whole FAQ file via C&P to master.

**Comment by Bananeweizen** [comment]
Go to the code tab of your forked repo, click on the branch dropdown below the commit count. Create new branch. There you go.

**Comment by Lineflyer** [comment]
German translation is done (bascially).

Please feel free to help and improve by catching my typos or grammatical errors.
I did all of this in the (late) evening and in a hurry, so I am sure there is room for improvement and correction. But the base is there.
