### ISSUE TITLE
Layout improvements - Summary

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo.github.io#12]
I don't want to create multiple issues as this is basically a summary of my subjective proposals for improvements to the now exiting draft of the new webpage. So I created this tickable list instead which can be later (if agreed) transfered into issues if needed:

- [x] The header section (with links to different pages) should be shown on each page 
- [x] The header should be static on top (not scrolling together with the content)
- [x] There has to be a back or home navigation which links back to the index.html
- [x] We could place the donate button in the same line as the links to GooglePlay, APK Download and give it a similar design.
- [x] External links (like to Github, etc.) should open in a new window

**Comment by SammysHP** [comment]
What do you mean with header section? Also the gray bar with the short description? I have a local branch from yesterday with some ideas.

I'm strictly against a fixed navigation. It would overlay the content. A home link is implemented in my local branch.

You can't download something with the donation button. So why make it to look like a download button and place it next to it?

The html standard has no way to tell the browser where to open links. The target attribute is deprecated. And this is good! I hate it whenever new tabs/windows are opened. If I want it, I can use ctrl/shift click or middle mouse button.

**Comment by Lineflyer** [comment]
Header: 
No, I was just refering to the selection of page on the top "Send2cgeo, FAQ,..."

Fixed navigation: 
It just came to my mind as I had to scroll up first each time before being able to select the next page. Don't know however what is a common style in this case.

Donation button:
To make it more visible, so that users wanting to donate do not need to search for it if it is lost in some column together with other elements. But we could also make a seperate page for donations with some explanations and add it only there...

Target:
I didn't know that `target=` is depracted...and honestly I don't understand it. If the link leads to something external I alwayws hate sites opening those inline instead of a new window. Reason is, when is browser around there and then e.g. learn, that this is not what I wanted I have to click "Back" several times to come back to where I started. But maybe its only my personal problem....

**Comment by SammysHP** [comment]
Header/navigation: done.

Donation button: let's wait for the new design of the sidebar.

Target: Please don't force me to add `target`. ;)

**Comment by Bananeweizen** [comment]
I'm against making the donation button even more prominent by placing it besides the download. We don't need that money. And for me it gives a bad taste to ask for donations together with the download. I want people to decide on their own about donations, and then to search for the ability to actually do that.

**Comment by Lineflyer** [comment]
So based on the comments lets consider the two remaining suggestions obsolete.
