### ISSUE TITLE
Keep GPS on while in c:geo and screen is off

### ISSUE THREAD

**Issue by andrixnet** [cgeo/cgeo.github.io#137]
c:geo only uses GPS while running in foreground and with screen on. 
c:geo's purpose, by nature, is to provide location (GPS) based functionalities. For such a GPS focused application, to release the GPS in several, requiring restarting the GPS (even if it is a hot restart) and waiting for a fix, is not the best way towards users. 

Also as I have pointed out in other issues I have reported, please do not design c:geo in ways like expecting/requiring users to have the latest, most expensive, top of the line devices.
Such behaviour is detrimental to c:geo and geocaching penetration to potential users in (at least) some countries that are not among the most highly developed (economically). 
**And this means more then _a few with low end devices_.**

Now to the technical points. 

I strongly disagree with the strategy described here: http://www.cgeo.org/faq.html#gps-powersafe or the resolution here https://github.com/cgeo/cgeo/issues/4879 . Let me explain:

1. requiring users to manage an external app to keep the GPS module on is by far **not** the best attitude to adopt towards users, for an app whose core functionality is based on GPS.
_It also adds complications and frustration to new or less IT experienced users._
2. many apps adopt a UI switch to turn on/off the GPS while using that app. Just look at apps like Locus, OruxMaps, Androzic, Pathaway, etc.
Keep GPS on until explicitely turned off by user, or application explicitely exited (see below).
**IMO c:geo should really consider this concept.**
3. time, position change and signal level since last turned on DO affect the hot start of any GPS. Time to fix may be significantly longer due to poor signal conditions (eg tall buildings, forest cover, valleys), as compared to maintaning an existing fix while signal level is decreasing.
4. don't assume user has very high performance device, even if most of the developer have.
_In fact I would suggest to the developers to routinely test both on high performance and mid-range (lower mid-range) devices to gauge the performance of c:geo in  a more realistic way._

**IMO, as a GPS oriented app, I would expect c:geo to perform at least the following way:**
- c:geo is open, has focus. `GPS on`. 
- c:geo is open, has focus, screen is off. `GPS on`. (by turning off the screen either manually or by timeout is by no means equal to the intention of turning off the GPS)

**c:geo running in background in the following scenarios:** 
- c:geo has focus and the user changes app that has focus (window manager)
- c:geo has focus and user goes to home screen
These may be considered `GPS on` optional, or based on setting. But still, GPS on if GPS turn on button in c:geo was used

**c:geo is closed by explicit user action:**
- c:geo has focus, from main screen, user presses "BACK". Exit the app. Optionally display exit confirmation.
- c:geo has focus. User chooses "Exit" menu option (to be implemented).
See many other dedicated GPS apps. 

Note: turning off GPS on some screens in the app is nonsense. I seriously doubt going through the settings menus for half a minute incurs such a significant energy saving. And going through the settings menu is by design a seldom used feature to begin with.
And me leaving c:geo open in the settings menu draining battery because GPS is on, now that is my fault and my responsability.

------------------------
Even as an experienced IT person, I still find it frustrating and hassling to having to rely on an external app and the associated management, just to maintain GPS fix while I go geocaching with c:geo.

**Comment by SammysHP** [comment]
There is no such thing as "running in background" or "closed explicitly" in Android. There would be a lot of guessing. See also:
https://developer.android.com/guide/topics/processes/process-lifecycle.html
https://developer.android.com/guide/components/activities/activity-lifecycle.html

I'm closing this issue as it is not related to the website or the FAQ.

**Comment by andrixnet** [comment]
I did not mean it to be about to the website or the FAQ. Those are just references. 

This is about searching with c:geo and having to wait for a fix every time I turn the screen on and the hassle of being required to install, use and manage GPS state by a separate app when GPS is a core function for c:geo.

Furthermore, I am talking about app behaviour from user perspective, not from the point of view of a developer. I am not a developer. 
I deem it important to maintain GPS on while app is running (from user perspective) in foreground, even if screen is off. Yes, screen may be turned off while I search for a geocache. 

I am also talking about closing (ie exiting) an app from the point of view of a user, having used other apps that have an explicit "Exit" function. That completely closes the app (regardless of what internal operations are performed and how the OS handles the resources used by that app) by ending all activities of the app, saving data and leaving everything in a consistent state. Next time the app is opened, regardless of method (tap on icon, recall from window manager, etc) it will perform ALL the initialization steps it needs for a proper start and complete startup. 

Some apps have a "tap BACK twice" to exit. (See OruxMaps, Locus, etc)
Some apps have an explicit "Exit" menu item (See Pathaway, Torque OBD scanner, etc)

Please reevaluate this issue and give serious consideration to this matter. Please don't trivially dismiss it.

Thank you.

**Comment by SammysHP** [comment]
I won't "reevaluate this issue" in the website repository.

**Comment by andrixnet** [comment]
Oh my, I totally missed that. I followed one issue link from another and absolutely missed out on the fact that the repository changed.
