### ISSUE TITLE
Use english screenshots

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo.github.io#14]
As the site is in english we should use english screenshots as e.g. located here: https://play.google.com/store/apps/details?id=cgeo.geocaching&hl=en

I was in preparation to submit a PR myself, but then only realized that via Github GUI it seems not possible to add binary files to a repo?!

**Comment by SammysHP** [comment]
Also you need to create the thumbnails. ;)

```
$ for i in {1..7}; do convert "$i.png" -quality 5 "${i}_thumb.jpg"; done
```

But thanks for the hint, I took them from the Play Store without looking at the language.
