### ISSUE TITLE
Using quick links to FAQ no longer working

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo.github.io#143]
On support mail we use quick links like this: http://faq.cgeo.org/#login-failed
These are no longer working after the design overhaul.

As these are used and refered since years it would be preferable to keep them working.
If it is not possible, I have to check where we use them and replace by the new URL.

**Comment by shroudedcode** [comment]
@Lineflyer Without the `.html` at the end of the `cgeo.org/faq` URL, the `faq.cgeo.org` URL is no longer shorter and therefore provides no real advantage. The redirect should still be changed.

**Comment by SammysHP** [comment]
@Lineflyer 
This code is hosted at @mucek4's server and should be adapted to the new format.

**Comment by Lineflyer** [comment]
For whatever reason this is working again.
I suspect it was implicitly solved while solving the unwanted redirect.

**Comment by shroudedcode** [comment]
@Lineflyer I would reopen this issue. While it now works, the redirect should also use the new permalink, whether the old one works or not.

**Comment by mucek4** [comment]
Redirect fixed.
