### ISSUE TITLE
No Logs

### ISSUE THREAD

**Issue by vsandre** [cgeo/cgeo.github.io#157]
No logs are shown for newly downloaded Geocaching.com Geocaches. The summary with found statistic is shown correctly but no logs.

**Comment by rsudev** [comment]
Hi vsandre, this is not the correct place for c:geo bugs, but for issues on the website. Please head over to https://github.com/cgeo/cgeo/issues for reporting your problem and at the same time supply as much information as possible which might help. Our issue template there should help you with that.
Thanks for reporting!

**Comment by Lineflyer** [comment]
@vsandre Please make sure you use the newest version of c:geo and you are logged in (Login OK shown on main screen).
