### ISSUE TITLE
remove ! from donation button

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo.github.io#16]
For my taste, the exclamation mark is making that a very strong request to donate. But I'd rather like to see that as just an option, not a request.

If I got it right, that button is an image. I'm not that experienced with CSS, but can't that be done by pure CSS without images nowadays?

**Comment by SammysHP** [comment]
Yes, it can be done. The question is if we want to use our own image or the default (yellow) PayPal donate button.

https://www.paypal.com/us/cgi-bin/webscr?cmd=_button-designer&factory_type=donate

**Comment by Bananeweizen** [comment]
I must admit I don't have a real opinion on that. On the one hand, having an own button might lead to a more straight look of the website. But on the other hand re-using a widely known button might lead to users more easily recognizing this as a normal paypal button. Both have some value.

**Comment by Lineflyer** [comment]
I also have no real preference, but I tend towards a button inline with the remaining design (without !).

**Comment by SammysHP** [comment]
Superseded by #105.
