### ISSUE TITLE
cgeo.org on HTTPS

### ISSUE THREAD

**Issue by mucek4** [cgeo/cgeo.github.io#160]
Since May 1st github supports HTTPS custom certificates.
https://blog.github.com/2018-05-01-github-pages-custom-domains-https/

Shall we switch that on?

**Comment by mucek4** [comment]
I tried, but it says "Not yet available for your site because the certificate has not finished being issued".
Looks like we need to wait a bit.

**Comment by kumy** [comment]
I'm disappointed that for this feature they have disabled IPv6 :cry:  https://github.com/isaacs/github/issues/354#issuecomment-385746014

**Comment by SammysHP** [comment]
The blog post says that it is enabled by default. And indeed it works: https://www.cgeo.org/

But it does not work without www (redirects to http://www.cgeo.org).

**Comment by mucek4** [comment]
Redirect is on my server (send2). I can fix that quickly.

**Comment by mucek4** [comment]
Now I entered setting again "Unavailable for your site because your domain is not properly configured to support HTTPS".
Maybe they have some glitches, or we have some misconfiguration ?
http[s]://cgeo.org/ now redirects to "https://www.cgeo.org/"

**Comment by Lineflyer** [comment]
AFAICS this is working now without a problem.
Feel free to reopen if you disagree.
