### ISSUE TITLE
TSL certificate expired

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo.github.io#163]
Seems the certificate has expired yesterday.
When accessing https://www.cgeo.org the browser give a security warning and blocks access (Firefox).

While opening http://www.cgeo.org is still possible, this is a blocker when calling http://faq.cgeo.org as this seems to always redirect to https://www.cgeo.org/faq

**Comment by kumy** [comment]
Isn t it github that host our website? @mucek4 any idea how to force renew the cert from GH site?

On May 16, 2018 12:52:32 PM GMT+02:00, Lars <notifications@github.com> wrote:
>Seems the certificate has expired yesterday.
>When accessing https://www.cgeo.org the browser give a security warning
>and blocks access (Firefox).
>
>While opening http://www.cgeo.org is still possible, this is a blocker
>when calling http://faq.cgeo.org as this seems to always redirect to
>https://www.cgeo.org/faq
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/cgeo/cgeo.github.io/issues/163

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by mucek4** [comment]
No. They still say our webpage "is not ready" to force SSL. Maybe this is the case. I'll redirect FAQ to http on our server again. For the time...

**Comment by SammysHP** [comment]
This is a problem with GitHub which is not able to renew the certificate.

**Comment by Lineflyer** [comment]
The redirect problem is solved.
However the certificate is still outdated.

**Comment by mucek4** [comment]
@SammysHP it could be due to error I have send to you. Maybe that is the reason they fail to update certificate. And yes, I have fixed the redirect.

**Comment by SammysHP** [comment]
No, the process does not work for several users.

**Comment by kumy** [comment]
Certificate has just been renewed, and the `Enforce HTTPS` option is now available.
