### ISSUE TITLE
link from features to FAQ

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo.github.io#17]
To make people more aware of the FAQ I suggest that we make the feature bullet list (and/or the remaining floating text) link to matching sections of the FAQ.

**Comment by Lineflyer** [comment]
Why not, but be aware that not every feature might have FAQ entries.
Maybe we should have a small manual lateron for all relevant features/screens.

**Comment by Lineflyer** [comment]
Looking at this again, I don't think it will work with the FAQ.
If you link some of the features (not all are covered) you will directly point the user to problems associated with that....thats not really good.

We would need an online manual for doing this efficiently, but I don't think that transforming the FAQ into a manual is meaningful.

**Comment by Bananeweizen** [comment]
Sounds reasonable. Maybe we can link to some screenshots instead?

**Comment by Lineflyer** [comment]
Superseeded by #144
