### ISSUE TITLE
Create user information page regarding the upcoming release (targetSDK change)

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo.github.io#177]
As mentioned in https://github.com/cgeo/cgeo/issues/7174 we should provide some background information to users about what is going on with c:geo at the moment.

I already started with a first draft here https://github.com/cgeo/cgeo.github.io/blob/master/userinfo_sdk_wip.md

This issue is a reminder, so I don't forget to continue. Anyway feel free to suggest additions/corrections.

**Comment by kumy** [comment]
We should not forgot to provide translated versions.

**Comment by Lineflyer** [comment]
I would rather stay with english here, unless we get this text onto Crowdin after finalization to get translation contribution. 

If we want to do this, we would need a localozation mechnism on the homepage, which we do not have yet (except for the FAQ). In order to keep the effort minimized we could simply add other languages below and provide anchors on top to link them.

But as this is only a one time info...lets keep it simple. IMHO english is enough (our regressions are hopefully not that much/intrusive).

**Comment by moving-bits** [comment]
Your "first draft" is very well done, thank you!

**Comment by Lineflyer** [comment]
Done
