### ISSUE TITLE
Add connector statistics in status page

### ISSUE THREAD

**Issue by samueltardieu** [cgeo/cgeo.github.io#188]
This is related to https://github.com/cgeo/cgeo/issues/7214 and https://github.com/cgeo/cgeo-status/issues/20. The client and server sides have been implemented, and now some Javascript code must be added to the status page.

As I was not able to setup a working Jekyll environment in the time I had scheduled for this, I'll let someone else (@SammysHP comes to mind) do it.

The new API is documented in cgeo-status routes.conf:

```
# Get counter by active connector
# The data is returned as a map with some special keys:
#   - _noinfo contains the number of clients with no connector information (older ones)
#   - _withinfo contains the number of clients with connector information
#   - _noconnectors contains the number of clients with empty (but present) connector information
```

One could display the percentage for every meaningful connector (keys not starting with `"_"` divided by `_withinfo` times 100), as well as the percentage of uses with no connector active (`_noconnectors` divded by `_withinfo` times 100).

**Comment by okainov** [comment]
Any update on this one?

**Comment by Lineflyer** [comment]
@SammysHP Do you have some spare minutes to take a look at it? Would be indeed nice to see, know that the client (c:geo) side is already up and running.

**Comment by Lineflyer** [comment]
@SammysHP  Some minutes available for this?
