### ISSUE TITLE
Describe spoilersync in user guide

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo.github.io#191]
This hidden feature was added years ago and I almost forgot it.
Will add a description in the user guide for this.

If anyone knows which tool (or function in e.g. GSAK) creates such structure, let me know so I can refer to it.

See:
https://github.com/cgeo/cgeo/blob/master/main/src/cgeo/geocaching/models/Geocache.java#L1863

**Comment by Bananeweizen** [comment]
If you have a piece of code, use the blame button to see why it was added. https://github.com/cgeo/cgeo/issues/3438

**Comment by Lineflyer** [comment]
@Bananeweizen Thanks! Still the final directory syntax is not clearly mentioned in the issue but only in source code comments..I needed some tries to get it working, thats why I wanted to write it down into the user guide now :)

**Comment by Lineflyer** [comment]
Done!
https://cgeo.droescher.eu/en/spoilersync
