### ISSUE TITLE
Reverse proxy on manual.cgeo.org is down

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo.github.io#192]
User manual currently not reachable via https://manual.cgeo.org

**Comment by bekuno** [comment]
Maybe also the reason why http://irclogs.cgeo.org doesn't work?

**Comment by mucek4** [comment]
Lars. Is there still a problem with this? On 30.4. I had some problems with IPv4.

**Comment by Lineflyer** [comment]
No, its up again after some time. IRC logs are also working again...maybe same problem.
