### ISSUE TITLE
Add HTTPS redirect

### ISSUE THREAD

**Issue by okainov** [cgeo/cgeo.github.io#193]
1. Type "cgeo.org" in browser
2. You will get HTTP version

Probably it makes sense nowadays to always unconditionally redirect to HTTPS to have one "canonical" website like `https://www.cgeo.org`

**Comment by mucek4** [comment]
I selected Enforce HTTPS on page, let's see when it will work.

**Comment by mucek4** [comment]
Looks like it works.
