### ISSUE TITLE
Add link to IRC channel

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo.github.io#20]
Moved from https://github.com/cgeo/cgeo/issues/2869

@Lineflyer:
Do we want to add an information to our IRC channel to the c:geo website ?
This would allow users to contact us for support via chat.

Most questions on support mail are easy to solve/answer, but for more complicated issues it would be nice to have a direct chat contact.
I don't think that many users would use it however for those with really difficult issues it would be helpful.

Can we add a link on http://www.cgeo.org/contact.html ?
I could also add a link to our FAQ (e.g. "I have a really difficult problem with c:geo. Where to get help?")

@rsudev:
I think it is a good idea to mention our IRC-channel on the website. But I would communcate it as developer channel, not so much as a support forum, because I would like to keep it primarily as our communication medium. This does of course not inhibit to invite anybody into the channel (as we often do already), but offering support their might raise expecations WRT to response times we probably will not fulfill.

@Bananeweizen:
Same opinion as rsudev.

**Comment by SammysHP** [comment]
IMHO we should link to the IRC from the README in cgeo/cgeo as it is intended primarily for developers.

**Comment by Bananeweizen** [comment]
It's the last sentence in the readme already.

**Comment by Lineflyer** [comment]
Covered by #30
