### ISSUE TITLE
Add link to c:geo status page

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo.github.io#21]
Moved from https://github.com/cgeo/cgeo/issues/1857 

@samueltardieu:
A link to the status page should be added

**Comment by samueltardieu** [comment]
Either that, or an iframe on `cgeo.github.io/status.html`. I would have `status.cgeo.org/status.html` be the iframe, and `status.cgeo.org` redirect onto the `cgeo.github.io/status.html` URL. This way, I wouldn't have to mimic the web site layout on status.cgeo.org.

**Comment by SammysHP** [comment]
Should the status page be public? Or publicly advertised?

**Comment by samueltardieu** [comment]
I see no problem with that, heroku can easily take the load.

2015-02-08 12:16 GMT+01:00 SammysHP <notifications@github.com>:

**Comment by Lineflyer** [comment]
I was asking the same in cgeo/cgeo#1857 as maybe some users might think, that collecting the usage statistics might not be suitable to be public. Maybe we could ommit the usage statistics but only show the collection of current releases and (if applicable) warning messages?

**Comment by SammysHP** [comment]
Is already merged in 1224c058f887317d568bda1a673b897d3981f6d4.
