### ISSUE TITLE
Add cache list markers to user guide

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo.github.io#210]
Release 2019.10.05 adds cache list markers. This change needs to be reflected in user guide.
- menu: cache list - manage list - set list marker
- added dot on icons in cache list and map

**Comment by Lineflyer** [comment]
First item is done in user guide for cache lists.

**Comment by Lineflyer** [comment]
Second item done in [https://cgeo.droescher.eu/de/cachemarkers]

**Comment by moving-bits** [comment]
@Lineflyer: Thanks for adding the feature info.
You may want to add that only up to two list markers are shown on the map icons, so if a cache is stored in at least three lists having list markers applied, not all markers will be shown.
Or can I somehow edit this on my own?

**Comment by Lineflyer** [comment]
Try if you can use Github Oauth login on the page. Could/should work. (but only when using the URL above, not from manual.cgeo.org).

**Comment by moving-bits** [comment]
OAuth seems to work, but the wiki complains afterwards:

![image](https://user-images.githubusercontent.com/3754370/69444877-8d28e100-0d51-11ea-9da4-6ccff9407726.png)

**Comment by Lineflyer** [comment]
Ah yes. I created an account for you. You should have received mail. In case this mail adress matches the one you use on Github, you should now also be able to use OAuth.

**Comment by Lineflyer** [comment]
Be sure to make changes in english first and german only afterwards. Otherwise the german page will show as outdated once you change the english afterwards.

**Comment by moving-bits** [comment]
Thanks for creating the account. Email addresses are different, but manual login works fine. Page is edited in EN and DE.
