### ISSUE TITLE
Complete description for UDC

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo.github.io#214]
Already contained in screenshot but description needs to be added once the feature is out on market.
See FIXME icon on https://cgeo.droescher.eu/en/mainmenu/lists#manage_caches

**Comment by bekuno** [comment]
How about also present this as special feature on the website main page (like the other 9 features)?

**Comment by Lineflyer** [comment]
Yes, maybe once its final.

**Comment by Lineflyer** [comment]
Done.
