### ISSUE TITLE
Add description for contacts-plugin

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo.github.io#217]
The documentation should have a point for the contacts plugin description

**Comment by Lineflyer** [comment]
What kind of documentation do you mean? The user guide?

**Comment by bekuno** [comment]
> What kind of documentation do you mean? The user guide?

Yes.
There are some points in the FAQ, but these are not good to find.

**Comment by Lineflyer** [comment]
WIP: https://manual.cgeo.org/en/contacts

**Comment by Lineflyer** [comment]
Duplicate of https://github.com/cgeo/cgeo-guide/issues/6
