### ISSUE TITLE
Add Brouter Howto to UserGuide

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo.github.io#219]
Instead of the FAQ entry
After done, FAQ entry should be linked to user guide (or entry removed)

**Comment by Lineflyer** [comment]
Done:
https://manual.cgeo.org/en/brouter
https://manual.cgeo.org/de/brouter

**Comment by bekuno** [comment]
The routed direction line is limited to ~35 km direct distance.
This could be added to the description.

**Comment by Lineflyer** [comment]
> The routed direction line is limited to ~35 km direct distance.

Can't it be configured to max. of 999km?

**Comment by bekuno** [comment]
Yes. Default is 10 km, max 999 km.
(my personally setting was 35km)
So we need only a hint for this setting in the c:geo settings - Map menu.

**Comment by bekuno** [comment]
I have tested with more distant targets. The routing was ok with 257 km direct distance, but no longer at 278 km.
Maybe there is a border in Brouter implemented.

**Comment by Lineflyer** [comment]
Done (the mentioned limit of 257km is nothing for the manual but rather a bug in c:geo or Brouter).
