### ISSUE TITLE
Include ohloh widget on web page

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo.github.io#22]
Moved from https://github.com/cgeo/cgeo/issues/1795

@Bananeweizen:
I suggest to include an ohloh widget on the cgeo home page. I always find that a good way of attracting potential new contributors to a project, if I see it on a web page of another project. It also allows outside people to "judge" the project a little bit (e.g. we currently list 49 contributors which is huge!)
I suggest to use the last one on this page: https://www.ohloh.net/p/cgeo2/widgets

Any comments?

@samueltardieu:
I second this.

@marco-dev:
+1

**Comment by SammysHP** [comment]
Please tell me where and I'll add it.

**Comment by Bananeweizen** [comment]
As the available widgets changed over time, I'm not sure which one I referred to initially. Right now, I find those called "Factoids and stats" or "Stats" quite nice.

I'm not good at design. But if I got the general idea right, then there is still space in the right of the two main columns on the homepage. I.e. below or above the donate button?

**Comment by SammysHP** [comment]
Too big and I'm not sure if you can change the colors in the iframe:

![20150208_154005](https://cloud.githubusercontent.com/assets/922874/6096926/f350cd3c-afa8-11e4-992d-a6ff9c3de016.png)

**Comment by Lineflyer** [comment]
What about moving this widget to another subpage under "Development".
There we could have
- The widget
- Explanatory link to Github pages
- Link to Crowdin for people interested in contributing translations
- Link to IRC developer channel
- (Maybe also the Nightly links)

This would unclutter the main page and bundle all development related ressource to a single subpage.

**Comment by Bananeweizen** [comment]
Yep, sounds good to me.

**Comment by Lineflyer** [comment]
See #30 then.
