### ISSUE TITLE
Link for fdroid download is counterintuitive

### ISSUE THREAD

**Issue by kumy** [cgeo/cgeo.github.io#222]
The homepage has links to download the apk from multiple location, with redirect to GPlay/github/or fdroid repo.

The one for fdroid pointing to https://fdroid.cgeo.org/ is not user friendly at all. This is a simple text page and has a link to the documentation, which need to be copy/pasted.

At least the page could be html and link clickable. Or redirect properly to https://www.cgeo.org/development.html#f-droid-repository. it happens here https://github.com/cgeo/cgeo-fdroid/blob/9b862076d9e9abe9c49a71091f763ff7bc245ac9/nginx/conf.d/default.conf#L30-L36

**Comment by bekuno** [comment]
Now we have a problem at the cgeo website.
On https://www.cgeo.org/development#f-droid-repository we have a link to https://fdroid.cgeo.org, so we link back to the same site. And https://fdroid.cgeo.org/nightly/ opens a 403 Forbiden site.
Therefore I reopen this Issue.

**Comment by kumy** [comment]
Good catch.

In fact those urls are for fdroid configuration only not for browsing.
We may start by removing the clickable links.

**Comment by kumy** [comment]
@bekuno do you approve changes? https://github.com/cgeo/cgeo.github.io/blob/issue-222/development.md#f-droid-repository

**Comment by bekuno** [comment]
I do not use F-Droid - so can not check it.
But the change looks good for me.

**Comment by kumy** [comment]
Let's merge then.
