### ISSUE TITLE
Add website for WhereYouGo

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo.github.io#223]
This could be similar to send2cgeo.

**Comment by Lineflyer** [comment]
I added a new repository to the cgeo organisation:
https://github.com/cgeo/WhereYouGo-website

The initial content is a modified version of the cgeo homepage. It for sure needs optical finetuning but is functional in itself.

At this moment its reachable under: https://www.cgeo.org/WhereYouGo-website/index.html
But we can add a CNAME to publish it under whereyougo.org

All follow up tasks can be added to the issues of that new repo:
https://github.com/cgeo/WhereYouGo-website/issues
