### ISSUE TITLE
Add Android 11 notice to FAQ

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo.github.io#237]
Add Android 11 warning notice to FAQ with HTML anchor being "#android11", as this in being linked to from c:geo's internal message window when running on Android >= 11.

Warning notice should inform about the following problem (coming from the enforcement of "storage spaces" in Android 11) - not necessarily with those words:

_Android 11 enforces a new way for storing data, which c:geo does not support yet. If you switch your system to Android 11, c:geo will not be able to access part of its data. This will most likely disable storing offline maps, importing/exporting data as well as backing up/restoring c:geo\'s database. Other effects may occur. We recommend to not upgrade to Android 11 for the time being._

**Comment by Lineflyer** [comment]
@moving-bits What is the anchor you used for the link? Its empty in your posting above.

**Comment by moving-bits** [comment]
The URL is `https://www.cgeo.org/faq#android11`

**Comment by Lineflyer** [comment]
Proposal for revised text based on test results for our FAQ:

Android 11 enforces a new way for storing data, which c:geo does not support yet. For the time being c:geo is using a legacy method to access data on the storage system (e.g. offline maps, imports/exports of GPX, backups, field notes) which seems to work well with Android 11. In parallel we are continuously working to implement the changes enforced by Google for the storage access in future c:geo versions. If you notice any issues on your Android 11 device, please kindly let us know on our support channels.

@moving-bits 
OK?
We should also change the in-app text, see https://github.com/cgeo/cgeo/issues/9225

**Comment by moving-bits** [comment]
Removed Android 11 warning on mainscreen (PR #9287) and updated changelog_master.xml
