### ISSUE TITLE
Add info about tracks and routes

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo.github.io#238]
c:geo can now
- import and display GPX track files
- import and display GPX route files
- create, display, sort and export individual (manual) routes

See the different map menus and settings for those features.

**Comment by Lineflyer** [comment]
Done.
Added only a short explanation of the relevant main menu entries of the map.
I would not want to go deeper here as the items below are more or less self explanatory:
https://manual.cgeo.org/en/mainmenu/livemap#top_bar_menu

**Comment by moving-bits** [comment]
Thanks for adding the info to the docs. IMHO the short form is sufficient.

For the "Individual route" part: Can you add a notice, that "long click" needs to be enabled in the map settings?

**Comment by Lineflyer** [comment]
Sure.

**Comment by Lineflyer** [comment]
Done.

**Comment by moving-bits** [comment]
Thanks 👍
