### ISSUE TITLE
different CSS for mobile

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo.github.io#25]
The new page looks okay on my mobile. But the page margins could be much smaller. Can we have different CSS for mobile and desktop?

**Comment by SammysHP** [comment]
Yes, that's easy - but I've never made a design for mobile, so I don't know where to start. :)

http://thesassway.com/intermediate/responsive-web-design-in-sass-using-media-queries-in-sass-32

**Comment by HoBi** [comment]
I can maybe help with that. The page need to set up a **viewport** (so the page on mobile will not scale and just stays in it's nature size) and also we need to update styles for the mobile using some `@media` queries.

**Comment by Bananeweizen** [comment]
@HoBi Feel free to give it a try.

**Comment by shroudedcode** [comment]
I guess we can close this issue now. I've included a `viewport` meta tag and also smaller paddings and margins for mobile devices using `@media` queries in the new site.

**Comment by SammysHP** [comment]
Indeed, thanks again!
