### ISSUE TITLE
Add internal routing engine to manual

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo.github.io#271]
Add info about internal routing engine to the manual when it's available in a released version. 

Some things to mention:
- how to activate & configure
- advantages of internal engine over external engine (automatic tile download + updates)
- links for advanced configuration of routing profiles: (see links provided in https://github.com/cgeo/cgeo/issues/10306#issuecomment-817652239)

**Comment by Lineflyer** [comment]
Moved to https://github.com/cgeo/cgeo-guide/issues/33

**Comment by moving-bits** [comment]
Ah, thanks. I need to try to remember which repo is for the manual, and which for other docs...
