### ISSUE TITLE
Use big badges

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo.github.io#31]
The font on the big badge for Google Play looks less fuzzy: https://developer.android.com/distribute/tools/promote/badges.html

**Comment by Bananeweizen** [comment]
Actually, with the same change, I would also like to remove the APK download link from the main page. Normal Android users should not even know about the possibility to download such files. And advanced users should also be able to find those APKs from a page which is not the main page.

**Comment by SammysHP** [comment]
Normal Android users would look in the Play Store. ;)

**Comment by Lineflyer** [comment]
It would also leave the APK download link on the main page. We are asked quite often as it is currently wuite hidden on the website.

**Comment by SammysHP** [comment]
Superseded by #105.
