### ISSUE TITLE
FAQ article for setting bat optimization to at least "Normal"

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo.github.io#316]
We had users on support where cache downloading in background stopped/failed as soon as they switched off the screen or changed to another app.
For all users the solution was, that their battery saving setting was set to "Eingeschränkt" which forbids any background activity.

**Comment by baiti** [comment]
Your post came just right as I am moving to Pixel 7 (Android 13). With respect to battery optimization it has three settings:

- Unrestricted
- Optimized
- Restricted

The default on a new device is to put the apps into "Optimized" category. It says: "Recommended for most apps". And this kills cgeo's background loader after a while. I had to put it into the "**Unrestricted**" category.

**Comment by Lineflyer** [comment]
Exactly. Optimized should be the minimum. Better set unrestricted for full functionality.

**Comment by Lineflyer** [comment]
This has been done meanwhile: https://www.cgeo.org/faq#13408
