### ISSUE TITLE
Title hidden behind navigation bar when jumping to anchor in FAQ

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo.github.io#41]
If you jump to an anchor used on the FAQ page (e.g. http://cgeo.github.io/faq.html#faq.UnkownLoca)
the relevant title will be hidden by the navigation bar on top. This might be quite confusing for users as they may only focus on the next section instead of the section they wanted to read.

Is it somehow possible to avoid that?

**Comment by SammysHP** [comment]
Nope. Only with Javascript.

**Comment by Lineflyer** [comment]
Maybe it would be enough to raise the transparency of the navigation bar a bit so that the hidden heading becoms more visible?
