### ISSUE TITLE
Add Support.html page

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo.github.io#43]
This should be added before we release the website.
It should contain a link to our support mail adress and some words about what details we need in order to help (e.g. System information, Detailed error description).

I remember, that I send around a mail with a proposal for an autoresponder for our support mail.
This text should be suitable here as well.
I will try to find it.

@SammysHP If you add the page as a markdown I can volunteer to fill it later on.

**Comment by Lineflyer** [comment]
@SammysHP Could you please check if you can embbed the social media links better than I did.

**Comment by Bananeweizen** [comment]
Somehow that page contains at least one duplicate paragraph. Can you recheck what you intended to do there?

**Comment by Lineflyer** [comment]
I added a introduction explaining the doubled information as it is divided into "Problems" and "Wishes".
