### ISSUE TITLE
Add send2cgeo.html

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo.github.io#44]
We need to add these pages 

https://send2.cgeo.org/home.html
https://send2.cgeo.org/howto.html 
https://send2.cgeo.org/script.html

the new website as well as a single page.
The script can be directly linked from Github sources IMHO.

The registration itself has probably to remain on send2.cgeo.org .

Remark:
I removed a basic explanation of send2cgeo from the FAQ as it should be better on this new page.

**Comment by SammysHP** [comment]
IMHO it is better to move send2cgeo to its own website.

**Comment by SammysHP** [comment]
Or single page on cgeo.org with iframe for registration (like our status page).

**Comment by Lineflyer** [comment]
The important thing for me is, that all the descriptions and texts are hosted on github.
The backend can/should/must be elsewhere.
