### ISSUE TITLE
Anti spam filter for support mail address needed?

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo.github.io#45]
It might be wise not to use a plain `mailto:` but some more spohisticated mail link method to avoid bots from scaning that mail address?`!

**Comment by SammysHP** [comment]
"more spohisticated mail link method"?! Yeah, we can remove the address. You can't protect a mail address.

https://www.google.com/search?q=support%40cgeo.org&gws_rd=ssl#q=support%40cgeo.org&tbs=li:1
