### ISSUE TITLE
Move banners to new website

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo.github.io#46]
Currently http://www.cgeo.org/media.html contains some banners.

The hyperlinks for banners promoted there might be used by people and should stay valid after changing to the new website.
If we keep offering them, we should also have a similar page on the new website.

**Comment by SammysHP** [comment]
Let's remove them. I've never seen one.

Funnily they are blocked by my adblocker. :)

**Comment by Lineflyer** [comment]
@SammysHP http://www.geocaching.com/profile/?guid=d11a3e3d-7db0-4d43-87f2-7893238844a6  ;)

**Comment by SammysHP** [comment]
Blocked by my adblocker. ;) It's a bad idea to place it in `…/ad/…` (or the filter is way too generic).

**Comment by Bananeweizen** [comment]
I vote for removing them from the old server (just so we can really get rid of it as much as possible), as I also expect them to be used only seldomly.

If this actually leads to users asking about a new location, then put them into a folder, create a simple .md file listing the banners and we are done.
