### ISSUE TITLE
Link back to page source

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo.github.io#47]
Would it be possible to always add a small link to each of our generated pages at the very end (or as an overlay somewhere else), where the URL is the source page on github? E.g. if I see a typo, I would really like to just click that link, afterwards the edit button and start fixing.

Now I always have to search the page in the repo first.

**Comment by SammysHP** [comment]
This would be possible only via hard coded links. Also some pages consist of multiple files that are included. And I don't think that the user (who is our target) is interested in such links.

**Comment by Lineflyer** [comment]
I also think, that this would be only useful for developers which is not the target group of the website.

We can add a paragraph on `development.html` that also the source of this website can be found on Github. So if someone wants to correct or add something he can send us a PR there or open an issue.

**Comment by SammysHP** [comment]
That would be a good idea!

**Comment by rsudev** [comment]
+1

**Comment by Bananeweizen** [comment]
I just stumbled over the new xtext documentation using this (see top right of every documentation page):
http://www.eclipse.org/Xtext/documentation/index.html

This is supported directly by jekyll and github:
https://github.com/jekyll/jekyll-help/issues/5
http://milanaryal.com/2015/adding-edit-on-github-links-to-github-pages-using-jekyll/

I therefore think we should really have this. It allows people to fork, edit, and create a pull request without needing to know our documentation _structure_. Just try it with the xtext link.

**Comment by Lineflyer** [comment]
@Bananeweizen I don't get the advantage. If I click the "Edit on Github" link on the xtext document it asks me first to create an account on Github..if I have one, it asks me to dork the repo, etc.
So it looks the same like a link to our repo which is already contained in `development.html`

**Comment by Bananeweizen** [comment]
Try it on _another_ page than the main page and you will notice what I mean: It directly brings you to an editor with that file already opened (if you are logged in with Github).

**Comment by SammysHP** [comment]
I have the feeling that there are no big issues with the current state.

**Comment by Bananeweizen** [comment]
I have a different feeling. :) Today I only wanted to update the translation URLs, and ended in committing roughly 20 additional typo fixes. I'm sure that some readers of the page saw those typos before, but didn't know how to change this...

**Comment by SammysHP** [comment]
… or didn't want to change them. ;)

(OK, there might exist some people who are interested in fixing typos on random websites, but IMHO that is a rather uncommon type of people.)

**Comment by kumy** [comment]
I m in favor of adding it, personally I looked for it many times

**Comment by Bananeweizen** [comment]
I'm fine with doing this on my own, if you accept some trial and error. I've never got the local stack for the github pages running on my machines, so I can't really test locally.

**Comment by SammysHP** [comment]
I wanted to assign myself but that doesn't work on the mobile page and I was in a hurry. Can do it if you want.

**Comment by Bananeweizen** [comment]
I really encourage you to do it. When I just looked in to this to start, I found myself not really knowing how to integrate this into the actual page at all in a common file.
