### ISSUE TITLE
Improve ohloh widget design

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo.github.io#50]
The widget has been placed on the development.html page but for sure needs design optimisations.

**Comment by SammysHP** [comment]
Yeah, but how? It's an iframe, we can't change its content.

**Comment by Bananeweizen** [comment]
The iframe is contained in a paragraph. If I set the CSS of that paragraph with color background, then it is  readable. Of course the paragrahp being white is too wide. So a complete fix would need to have some size fitting element around the script, and then settings its color.

**Comment by SammysHP** [comment]
Fixed in d5461608da2c0564ec2f42fd3b04731e51dbfa71.

**Comment by Bananeweizen** [comment]
Very nice.
