### ISSUE TITLE
Remove Nightly and Status from Main Navigation

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo.github.io#51]
Those items are now included on development.html.

I did not yet remove anything as I wanted to wait for feedback first.
Especially the nightlies might become harder to find if they are removed, so I am not sure about that.

**Comment by Bananeweizen** [comment]
I'm fine with that change. As I said before, normal users shouldn't know about this, so removing is okay. Advanced users will find it independent of where we put it. And in support cases we provide a link to the nightly, so it doesn't matter there.
