### ISSUE TITLE
Implement send2cgeo server functions 

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo.github.io#56]
An initial send2cgeo.html was created, but the server functions still need to be implemented in a good way (e.g. iframe).

**Comment by Lineflyer** [comment]
As discussed with @mucek4 today he will create a simple test page tomorrow to test if an iframe would support the necessary cookie operations for the service.
We can try this out on the github page then.

**Comment by mucek4** [comment]
http://download.cgeo.org/cookieTest.php

**Comment by SammysHP** [comment]
It works (of course). There might be an issue with some browsers and/or configuration (third party cookies must be allowed, [P3P](http://www.w3.org/P3P/) in IE).

**Comment by Lineflyer** [comment]
http://lineflyer.github.io/send2cgeo.html

Yes, it works but cookies for third party need to be allowed as @SammysHP wrote:
But that is anyway a precondition for send2cgeo to work on geocaching.com.

BTW: I need to check if this is covered in the installation instruction.

@mucek4 So you can create a simple page with Register, Name browser, Add device, Maintain device" based on that which we can embedd as iframe.

**Comment by Lineflyer** [comment]
@mucek4 
Hope you returned home safely...

If you could make a webpage on your server with just these buttons we can embbed it as an iframe on the new page and we are done IMHO:
![](http://i.imgur.com/Ey6HCCU.png)

**Comment by mucek4** [comment]
Ok. I created page with requested with only 1 problem. I didn't think about the cookie and moved everything to subdomain. Please check what do you think about this implementation and if it looks OK I'll created it on the same subdomain.

**Comment by Lineflyer** [comment]
I think it looks quite good for the beginning.
We can start with that IMO.

Right now it shows me as unregistered but I should be registered....but I guess that is because of the cookie?!

**Comment by Lineflyer** [comment]
One more note:
@mucek4 
For the PIN screen please change the prompt as follows:
"To add a device to your browser you have to generate a PIN on your device.
Please enter the generated PIN here and select "Add" to register the device."

For the browser name prompt please correct:
"To easily identify your browser you can set a name fot it. Just fill in the name for it and select save. You can change the name at any time"

**Comment by mucek4** [comment]
If ti looks OK I have to "port" that to send2 domain to re-use the cookie. I'll do that

**Comment by Lineflyer** [comment]
Does changing the subdomain have any influence about client and script functionality? Because these will still target send2 subdomain.

**Comment by mucek4** [comment]
Changing the domain is not an option at all. but here I could just copy all files on server and changed them. Now I have to copy it back to original site when we do a switch or integrate so both systems can run in paralel.

**Comment by Lineflyer** [comment]
Understood.

@SammysHP 
Any concerns about the design of that iframe?

**Comment by SammysHP** [comment]
Switch link and text color as links are orange.

**Comment by Lineflyer** [comment]
Status:
Almost done.

Only some redesign still needed as mentioned on IRC:
```
[11:11] <Lineflyer> basically the send2 logo needs to be a little smaller so that the menu fits right next to it instead of being breaked down some rows.
[11:13] <Lineflyer> And in https://send2.cgeo.org/api/device.html I would like you to remove the explanatory text with the link. Just "Add a device" and the "Enter your PIN here".
[11:13] <Lineflyer> also on this page the layout should be adapted to fit the menu right of the PIN field
[11:14] <Lineflyer> and thats it AFAICS now
```

**Comment by mucek4** [comment]
I think it's done.

**Comment by Lineflyer** [comment]
Done!
