### ISSUE TITLE
Add social network links to homepage

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo.github.io#6]
Like FB, G+, Twitter

**Comment by Lineflyer** [comment]
For Facebook we can use premade code from https://developers.facebook.com/docs/plugins starting from a simple like button, over like button with follower count up to a scrollable frame showing the latest posts and optionally latest followers. Each available in HTML5, XFBML, IFRAME or simple URL.

Just let someone know what is needed and each editor of our Facebook page can create it under the above mentioned URL.

**Comment by SammysHP** [comment]
I smell tracking... No, let's use a simple image (hosted in our repo) with a link.

**Comment by Lineflyer** [comment]
Sure it is tracking for users who are logged in to Facebook and visting our page, but that what they want isn't it.
On the other hand all users coming to our page will have the benefit to see the latest FB-posts. So we would have an integrated newsfeed without additional effort, which I would like very much.

**Comment by SammysHP** [comment]
All other users are tracked as well.

**Comment by Lineflyer** [comment]
mmh..OK.

However here is an example of it in my local repo (not well designed of course):
http://lineflyer.github.io

**Comment by SammysHP** [comment]
And now I have a cookie, they know, which sites I visit (all, that includes Facebook stuff), the know, how many people visit our site etc.
