### ISSUE TITLE
FAQ update not possible in play store

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo.github.io#60]
I read the question on facebook about not being able to upgrade (due to no upgrade being shown). Actually a friend of mine had the same issue with the March 31 upgrade. I suggest we add a FAQ about rebooting the phone to let the play store sync again, which Lars mentioned as solution.

**Comment by Lineflyer** [comment]
I will not apply this to the old FAQ as I hope we get the new website alive soon

**Comment by Bananeweizen** [comment]
That was what I meant of course. :)
