### ISSUE TITLE
Translate FAQ

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo.github.io#72]
I would like to add a german (and other) translations of the FAQ. 

This would IMHO only require:
- A means to select the desired language on the FAQ page or (preferably) auto detect the language from the browsers preference
- Another `yml` file for each language using the same anchors

Is this technically possible here on Github?

**Comment by SammysHP** [comment]
Language detection only with JavaScript. Then there are two possibilities:

a) `/faq_en.html`, `/faq_de.html`…
b) `faq.html` with content generated by JavaScript.

**Comment by Bananeweizen** [comment]
I'm not so sure if a separate file is really a good idea. If you put the different language entries all in the same file then
* it is easier to compare them (as author/translator), even in the browser editor
* we can add logic to output the English version if no translated version is available.

**Comment by SammysHP** [comment]
Creating multiple html files would be possible by creating multiple files in jenkins. But when you link to the FAQ you link also to a specific language.

So my idea: Create the html page as it is now and add a JSON array containing all translation. Then the English entries can be replaced with the detected language via JavaScript.

**Comment by mucek4** [comment]
What about adding all content in single HTML file and hiding content with CSS/JavaScript? If JS would be disabled everything would be visible instead of nothing?

**Comment by SammysHP** [comment]
The English text would be visible like it is now. The JavaScript would replace the English text with the translation (where provided).

**Comment by Lineflyer** [comment]
For me it would be important that it is possible to use the same URL and the desired language can then be selected by the user (or automatically selected).
So that we can always give out e.g. http://www.cgeo.org/faq.html#ios and the user is directed to the correct language anyway.

**Comment by Lineflyer** [comment]
FYI: There are some volunteers sometimes contacting us via support or FB for translation...however preferably the translation should be hosted on Crowdin.

**Comment by SammysHP** [comment]
Here it is. Please test it. Should work, but the code (or the way it works) is ugly. It sends all translations to the browser (in hidden containers) and uses JavaScript to show the specific language. Without JS only English is shown.

@Lineflyer There's some work in the FAQ file:
- Apply the new format to the old FAQ (I already started)
- Translate everything

**Comment by brainscript** [comment]
@SammysHP And how can the user select the language?

**Comment by SammysHP** [comment]
That is done automatically depending on the language set in the browser.

**Comment by brainscript** [comment]
Somehow that doesn't work for me ...
... although I set the preferred language in Firefox to German.

**Comment by SammysHP** [comment]
a) There are no translations yet (except for one paragraph), so mostly English is shown.
b) It requires JavaScript.

**Comment by brainscript** [comment]
I do have JavaScript (and I'm not using NoScript), `console.log(navigator.language)` returns `de` and "Temporary issues" is still English although it should be translated to "Vorübergehende Probleme".

**Comment by SammysHP** [comment]
Any errors in the console? Are you sure that you are on the correct branch? This is not on master yet.

https://github.com/cgeo/cgeo.github.io/tree/translation

**Comment by brainscript** [comment]
@SammysHP Forget about it. :smile: I didn't use branches before, so I didn't recognize that.
Is it possible to preview pages from different branches using GitHub pages?
Because due to the fact that I had to reinstall my OS, I currently haven't got Jekyll installed.

**Comment by SammysHP** [comment]
Nope, that's not possible.

**Comment by Lineflyer** [comment]
@SammysHP
Can you document (e.g. in the Wiki) what exactly needs to be done for the two tasks you mentioned above?

**Comment by SammysHP** [comment]
@Lineflyer 
Just look at the new format of `_data/faq.yml` in #109. It is:

```
- id: section-id
  title:
      en: English section title
      de: German section title
  items:
      - id: it-of-entry
        en:
            title: English title
            content: |
                English text body
        de:
            title: German title
            content: |
                German text body
```

If somebody wants to transform it into the new format, just do it and post it somewhere – I'll update the pull requests with the new content.

**Comment by Lineflyer** [comment]
Oh. I did not see #109 yet. Now I understand.
Is there a way a automatically proccess the FAQ on `master` to get a final hierarchy for `en`. If this is in `master` I could sequentially add german translations as time permits.

**Comment by SammysHP** [comment]
Unless @samueltardieu has some awk/sed trick to convert it, it might be faster to do it by hand. ;)

**Comment by kumy** [comment]
It's yaml, it could be easily parsed and reformated. I could write a python script for that.

**Comment by kumy** [comment]
@SammysHP Here is a small script for the conversion: https://gist.github.com/kumy/fac092e097a233a308ed115e6361371b

**Comment by SammysHP** [comment]
Nice, thank you! I'll convert the faq tomorrow and merge the PR.

**Comment by Lineflyer** [comment]
Thanks for your effort @kumy 

As soon as @SammysHP merged the new format and the needed Javascript I will begin adding german translations as time permits.

**Comment by SammysHP** [comment]
@kumy 
Can you please check your script or even send me the faq.yml file?

```
Traceback (most recent call last):
  File "./cgeo-faq-convert.py", line 52, in <module>
    convert(OldFaq(faq_entry))
  File "./cgeo-faq-convert.py", line 35, in convert
    print(re.sub(r'^', '                ', item['content'].encode('utf-8'), flags=re.MULTILINE))
  File "/usr/lib/python3.5/re.py", line 182, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: cannot use a string pattern on a bytes-like object
```

**Comment by kumy** [comment]
@SammysHP see #112
(I wrote the script for python 2)

**Comment by SammysHP** [comment]
@kumy 
Sorry, wrong format. `items:` is missing. Can you update your PR? Otherwise I can run the script tomorrow with python 2.

**Comment by kumy** [comment]
@SammysHP PR and gist udpated :)

**Comment by kumy** [comment]
And gist also updated for the `TypeError: cannot use a string pattern on a bytes-like object` error. (I hope)
