### ISSUE TITLE
Readd c:geo banner pictures to Github

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo.github.io#78]
We received some requests about missing banners and logos from our website.
Can't we just put the original content of `http://www.cgeo.org/content/ad/` to the very same directory on Github?

IMHO no need to make a HTML page for that, but just to reenable the access to these banners?

**Comment by Bananeweizen** [comment]
If this is just a matter of copying, that sounds very reasonable to me (even though we decided different before).

**Comment by SammysHP** [comment]
We can copy them, but do not link them on the website. That would be fine. Please give me a link to the files with the exact path.

**Comment by SammysHP** [comment]
Found the image in our Bitbucket repository.
