### ISSUE TITLE
avoid white background flicker

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo.github.io#79]
If you load the website, the background is shortly shown totally white, and after the CSS (or whatever) has been loaded, if switches to black. Can we add a meta tag in the HTML header for black background color to avoid that? (I'm not so much into HTML, so maybe the solution must be something totally different).

I have seen that most prominently on devices where I never loaded the website before (probably because the non existing cached content maximizes the time until the CSS is applied).

**Comment by samueltardieu** [comment]
Or maybe we should use a light background, as most sites do for a good reason :)

**Comment by SammysHP** [comment]
Light background? c:geo is a dark app. :D 

It's simply a missing default color in the CSS. I'll add it. And nope, no styles in HTML please. ;)

**Comment by samueltardieu** [comment]
The era where every application was different on Android is over. We really should align to common guidelines, and adopt material design.

**Comment by SammysHP** [comment]
Yep, we should and apps that I create nowadays follow Material style. But as long as c:geo does not use Material we should stay consistent with the website.
