### ISSUE TITLE
Have a branch for drafts

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo.github.io#8]
As the content of `master` is alyway online it would be helpful to have branch `draft` for preparation of site changes which e.g. need to be synchronized to a certain release of the app.
While most changes IMHO should go directly to `master` the `draft` should be used only for planned updates of the site (e.g. release depending, major rework,etc.)

Would this be a valid method of working with this repo?

**Comment by Bananeweizen** [comment]
Sounds quite reasonable to me. But how would we actually preview the rendered HTML files? They are not published by the webserver, as far as I understood yesterdays experiments.

**Comment by SammysHP** [comment]
Yes, only the master branch is accessible.

**Comment by Lineflyer** [comment]
Yes, review can be done locally. As written above, a `draft` branch would be only used for planned switches of the content which need preparation (e.g. release depending, major rework,etc.).

I would have assumed that also via Github GUI it would be possible to see the content of a branch other than `master` by making it the default branch. But tests show, that this seems not possible.

**Comment by Bananeweizen** [comment]
As long as everyone doing such changes does preview them in his local clone (by renaming the local clone to <userid>.github.io) we should be fine.
