### ISSUE TITLE
Links from status.html not working

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo.github.io#85]
- Open www.cgeo.org/status.html
- Click on any link in row "Kind"

Result:
Empty page shown (only headers)

**Comment by samueltardieu** [comment]
Cannot reproduce. All links appear valid to me. What are the URL you are seeing?

**Comment by kumy** [comment]
For me if I click the first link, nothing happen.
With Firebug I see
`Load denied by X-Frame-Options: https://play.google.com/store/apps/details?id=cgeo.geocaching does not permit cross-origin framing.`

On Firefox 38.

**Comment by Bananeweizen** [comment]
Similar issue with Chrome. Can reproduce it on the playstore links. Console says:
Refused to display 'https://play.google.com/store/apps/details?id=cgeo.geocaching' in a frame because it set 'X-Frame-Options' to 'SAMEORIGIN'.

**Comment by samueltardieu** [comment]
I'll add CORS. I forgot that my browser is configured to ignore this in development mode.

**Comment by Lineflyer** [comment]
@samueltardieu Confirmed working for me (as you asked for that on IRC).
