### ISSUE TITLE
Use Jekyll

### ISSUE THREAD

**Issue by SammysHP** [cgeo/cgeo.github.io#9]
Currently we have a single static page. This won't work with our complex content so we should use jekyll, a static page generator that is used for processing GitHub user pages.

**Comment by Lineflyer** [comment]
Complex content? You mean the FAQ?

I would also rather drop other content like Changelog,... which is also available elsewhere (i.e. on Github).

**Comment by SammysHP** [comment]
Well, do you want more than one single site? Then we need Jekyll.

**Comment by SammysHP** [comment]
Wow, installing jekyll is a pain. Now I have a mess of dependencies in my home and it still does not work.

**Comment by Bananeweizen** [comment]
> Well, do you want more than one single site?

No, I don't. I just want multiple pages. I guess you meant the same? http://grammarist.com/usage/website-web-page/

**Comment by SammysHP** [comment]
Yes, thanks.

**Comment by Lineflyer** [comment]
Excuse my non-knowledge at this point:
If we just want multiple pages, we could just place them right away in the root dir as *.html and link them from the main page. I am sure you are right and I miss some important point, I just want to understand.

What exactly is the difference in using Jekyll? I tried to read about it and understood only a little.
The FAQ e.g. could be a rather plain html using `<p>` for each entry...

**Comment by SammysHP** [comment]
Yes, you're missing the fact, that there is a design. The complete HTML framework, the header etc.

**Comment by SammysHP** [comment]
Ok, basic jekyll framework is done. But still much missing.
