### ISSUE TITLE
www2.cgeo.org still used

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo.github.io#91]
Open the URL cgeo.github.io (as in the description of the repo). This leads to www2.cgeo.org, which is dead. I have no idea, where this needs to be configured. github? cgeo DNS?

**Comment by SammysHP** [comment]
Here: https://github.com/cgeo/cgeo.github.io/blob/master/CNAME

But it is already www.cgeo.org

**Comment by Bananeweizen** [comment]
Indeed, cleaning the browser cache helped.
